secret = "77810670761305411852818644688495718724443020692037627932938912199082614642"
blinder = "299078936038283580531875626602162819698843318883219782554565529030942577790"
zk_commitment = "0x392fc60d0605f3e530e177f962edfce350c2b6b31ac572596ea7df48a5c979c"
nullifier_hash = "0x17f60ec6800f01b40ee323a5a7c13352ef92883a0f6ba1e2b7c8944a2c903c5a"
denomination = "0"
