secret = "432035842891444785754470669236687503739683847847863904604332007357433150650"
blinder = "395663910387193934172524227874534951169910849619924980010160044607526060586"
zk_commitment = "0x19da5326d3d3721f3b82997562a73cfc0fd528c63059ec58b99aeff49bcaa2b0"
nullifier_hash = "0x2786597f5143b749cbdfb79c5fd9fbf93ba953259155439202a5896b8c45c8a4"
denomination = "2"
